SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, O.NAME, (O.DATETIME - I.DATETIME) TIME
        FROM ANIMAL_INS I,ANIMAL_OUTS O
        WHERE I.ANIMAL_ID = O.ANIMAL_ID ORDER BY TIME DESC) T
WHERE ROWNUM <= 2;